"""Read completed data, validate preservation and write final artifacts. No simulation."""
import json,pathlib,hashlib,os,subprocess,collections,math
HERE=pathlib.Path(__file__).resolve().parent

def read(f):return json.loads((HERE/f).read_text())
def main():
 r1=read('round1/result.json');ext=read('round2_extension/result.json');val=read('round3/result.json');a=read('round2/analysis.json');b=read('round3/analysis.json');old=read('old_readiness_at140000.json');allpairs=a['pairs']+b['pairs'];identified=[x for x in allpairs if x['identifiable']]
 seed5=[x for x in a['pairs'] if x['seed']==20005];s5=next(x for x in seed5 if x['actions']==['A_BC','C_POST1250'])
 metrics={}
 for head in ['Q1','Q2','Qmean']:
  correct=sum(x['critics']['ready'][head]['classification']=='CORRECT_RANKING' for x in identified);wrong=sum(x['critics']['ready'][head]['classification']=='WRONG_RANKING' for x in identified)
  metrics[head]={'correct':correct,'wrong':wrong,'denominator':len(identified),'pairwise_accuracy':correct/len(identified) if identified else None,'mean_advantage_error_identifiable':sum(x['critics']['ready'][head]['advantage_error'] for x in identified)/len(identified) if identified else None,'mean_advantage_error_all_pairs':sum(x['critics']['ready'][head]['advantage_error'] for x in allpairs)/len(allpairs)}
 bothwrong=[x for x in identified if all(x['critics']['ready'][h]['classification']=='WRONG_RANKING' for h in ['Q1','Q2'])]
 indbothwrong=[x for x in b['pairs'] if x['identifiable'] and all(x['critics']['ready'][h]['classification']=='WRONG_RANKING' for h in ['Q1','Q2'])]
 newepisodes=r1['episodes']+ext['episodes']+val['episodes'];trace_checks=[];steps=0;postfork_clip_max=0.
 for stage in ['round1','round2_extension','round3']:
  d=read(stage+'/result.json');c=d['env_contract'];assert all(c[k]==4 for k in ['initialized','used','closed']);assert c['exitcodes']==[0]*4 and d['model_hashes_unchanged'];assert d['actor_updates']==d['critic_updates']==0
  for trace in (HERE/stage).glob('rep*_trace.jsonl'):
   groups=collections.defaultdict(list)
   for line in trace.open():
    x=json.loads(line);groups[x['seed']].append(x)
   futures=int(trace.name.split('_')[0][3:]);branch=trace.name[trace.name.index('_')+1:-len('_trace.jsonl')];reg=read(stage+'/preregistration.json')
   for seed,rows in groups.items():
    e=next(x for x in d['episodes'] if x['seed']==seed and x['branch']==branch and x['future_rng']==reg['future_rng_seeds'][futures]);rows.sort(key=lambda x:x['timestep']);assert len(rows)==e['length'];assert [x['timestep'] for x in rows]==list(range(len(rows)))
    g=sum(.99**(x['timestep']-e['fork'])*x['reward'] for x in rows if x['timestep']>=e['fork']);assert abs(g-e['mc_from_fork'])<1e-10
    assert all(x['reward'] in [0,1] and all(abs(z)<=1 for z in x['action_executed']) for x in rows)
    assert rows[-1]['terminated'] or rows[-1]['truncated']
    for x in rows[e['fork']+1:]:postfork_clip_max=max(postfork_clip_max,max(abs(y-z) for y,z in zip(x['action_raw'],x['action_executed'])))
    steps+=len(rows);trace_checks.append({'stage':stage,'seed':seed,'future_rng':e['future_rng'],'branch':branch,'length':len(rows),'mc':g,'success':e['success']})
 assert len(trace_checks)==144 and len(newepisodes)==144;assert postfork_clip_max==0
 saved=read('safety_before.json');changes=[]
 for f,h in saved['files'].items():
  path=pathlib.Path(f)
  if not path.exists() or hashlib.sha256(path.read_bytes()).hexdigest()!=h:changes.append(f)
 assert not changes,changes
 procs=subprocess.check_output(['ps','-eo','pid,ppid,args'],text=True).splitlines();residual=[x for x in procs if any(s in x for s in ['acceptance_runner.py round','validation_runner.py round','multiprocessing.spawn','multiprocessing.resource_tracker']) and int(x.split()[0])!=os.getpid()]
 assert not residual,residual
 safety={'hashed_files':len(saved['files']),'changed':changes,'fusion_exists_before':saved['fusion_exists'],'fusion_exists_after':pathlib.Path('fusion_result.json').exists(),'residual_diagnostic_processes':residual,'trace_checks':trace_checks,'new_episodes':len(trace_checks),'env_steps':steps,'continuation_raw_clip_discrepancy_max':postfork_clip_max,'git_status_after':subprocess.check_output(['git','status','--short'],text=True)}
 (HERE/'safety_after.json').write_text(json.dumps(safety,indent=2))
 classification={'REJECTED':['SEED20005_UNIFORM_6OF6_RETURN_DECLINE','BEHAVIOR_CORRELATION_AS_SUFFICIENT_ACTION_ADVANTAGE_ACCEPTANCE'],'CONFIRMED':['STRICT_MATCHED_SEMANTICS_PROTOCOL_COMPLETED','SEED20005_Q1_Q2_PREFER_CANDIDATE_WITH_5_OF6_NEGATIVE_REALIZATIONS','OLD_READINESS_DOES_NOT_TEST_CONDITIONAL_ACTION_RANKING'],'SUPPORTED':['SEED20005_NEGATIVE_EMPIRICAL_MEAN_ADVANTAGE_NOT_CONFIDENTLY_IDENTIFIED'],'INCONCLUSIVE':['SEED20005_TRUE_EXPECTED_ADVANTAGE_SIGN','RELIABLE_GENERAL_COUNTERFACTUAL_RANKING','UNIQUE_UPSTREAM_COLLAPSE_CAUSE']}
 if indbothwrong:classification['SUPPORTED'].append('INDEPENDENT_CONDITIONAL_MISRANKING_UNDER_EXPLORATORY_PER_PAIR_CRITERIA')
 summary={'status':'COMPLETE_STOPPED','original_goal':'NOT_CERTIFIED','unique_upstream_root_cause':'INCONCLUSIVE','scope':'completed only3supplemental discovery streams and1preregistered independent batch;no extra experiments','contexts':8,'named_candidates_per_context':4,'unique_executed_candidates_per_context':3,'readiness_candidate_alias':'BC','unique_strict_action_pairs':len(allpairs),'paired_rng_comparisons':sum(len(x['delta_g_samples']) for x in allpairs),'identifiable_pairs':len(identified),'real_return_tie_pairs':sum(x['real_return_tie'] for x in allpairs),'unresolved_non_tie_pairs':sum(not x['identifiable'] and not x['real_return_tie'] for x in allpairs),'ready_metrics':metrics,'seed20005':seed5,'independent_seeds':[20088,20089,20090,20091],'independent_summary':b['summary'],'independent_pairs':b['pairs'],'twin_common_wrong_identifiable':len(bothwrong),'independent_twin_common_wrong_identifiable':len(indbothwrong),'twin_positive_Q_negative_MC_realizations':sum(x['twin_wrong_realizations'] for x in allpairs),'MC_evaluation':'SEMANTICS_MISMATCH;NO_RANK_ACCURACY_OR_ADVANTAGE_ERROR_ASSERTED','classification':classification,'statistical_limits':'Per-pair unadjusted median sign test plus approximate small-sample mean t interval;not a familywise nonparametric confidence claim on expected advantage. Twelve dependent pairs per batch.','actor_updates':0,'critic_updates':0,'production_modified':False,'formal_checkpoints_modified':False,'formal_training':'STOPPED','simulator_contracts':[d['env_contract'] for d in [r1,ext,val]],'new_episodes':len(newepisodes),'env_steps':steps,'wall_seconds':[d['wall_seconds'] for d in [r1,ext,val]],'safety':'safety_after.json','old_readiness_actual':{k:old[k] for k in ['env_steps','qmean_mc_spearman','td_e1_mae','td_e2_mae','numeric_finite','overall_ready_v2']},'next_step_proposed_only':'If authorized later,resolve conditional expected advantage uncertainty on recorded conflict contexts before choosing any supervision or approximation repair.','final_markers':['CRITIC COUNTERFACTUAL ACCEPTANCE TEST COMPLETE','FORMAL TRAINING REMAINS STOPPED']}
 (HERE/'final_summary.json').write_text(json.dumps(summary,indent=2,allow_nan=False))
 write_report(summary,a,b,safety)
 intro=json.loads((HERE/'report_intro_template.json').read_text()).format(ind_pairs=b['summary']['all']['unique_action_pairs'],ind_valid=b['summary']['all']['identifiable_pairs'],ind_ties=b['summary']['all']['real_return_tie_pairs'],ind_unresolved=b['summary']['all']['unresolved_non_tie_pairs'],ind_wrong=len(indbothwrong),ind_verdict=('SUPPORTED: independent local misranking under exploratory per-pair criteria;no universal claim.' if indbothwrong else 'INCONCLUSIVE: no identifiable independent common-twin error;no universal claim.'),total_valid=len(identified),q1_accuracy=metrics['Q1']['pairwise_accuracy'],q2_accuracy=metrics['Q2']['pairwise_accuracy'])
 report=HERE/'FINAL_REPORT.md';report.write_text(intro+report.read_text(),encoding='utf-8')
 print(json.dumps({k:summary[k] for k in ['contexts','unique_strict_action_pairs','identifiable_pairs','real_return_tie_pairs','unresolved_non_tie_pairs','ready_metrics','independent_twin_common_wrong_identifiable','new_episodes','env_steps']},indent=2))

def write_report(s,a,b,safety):
 p=s['seed20005'][0];v=b['summary']['all'];d=a['summary']['all'];wrong=s['independent_twin_common_wrong_identifiable'];lines=['# Stage3-V6 mean2q/multi_q Critic counterfactual acceptance','',
 '## Direct answer',
 'Reliable conditional counterfactual action-value evaluation is **NOT CERTIFIED**. Seed20005 exhibits repeated realized Q/return sign conflicts, but additional streams show one positive reversal and its mean-advantage sign remains INCONCLUSIVE. Independent results below are reported exactly, without adding contexts or claiming universality.',
 '', '## Completed scope and protocol',
 'Round1 discovery: seeds20005t199,20008t205,20028t282,20031t282;future streams41001-41003. Round2 adds only41004-41006 on exactlythe same contexts and reuses Round1. Round3 is the only independent batch: seeds20088-20091,streams42001-42006. Fork rule is first BC gripper signtransition after120,otherwise350,selected before outcomes. No extra experiment after this batch.',
 'Independent seeds were the first unused contiguous block advancing4from20040,excluding allprior final_summary report mentions. They differ from Stage2 training/validation10000-10099,Stage3 training seedbase30000,and original formal evaluation20000-20009. All reference failures retained.',
 'Four named candidates: A BC/reference,B readiness,C existing normally updated post1250Actor,D half raw-action interpolation followed by feasible clipping. This need not be the exact midpoint of separately clipped A/C in every boundary dimension. Readiness weights exactly equal BC and target_actor;B is an exact A alias under coupled sampling,so three unique executed candidates and three unordered pairs per context. Raw and executed actions recorded;all executed actions bounded [-1,1].',
 'Only fork candidate changes. Exact exposed MuJoCo integration/controller/cache/NumPyRNG snapshot,history,executed previous actions,episode progress,reference RNN and parent RNG hashes matched. Deterministic prefix replay checked against historical observations in discovery and strict cross-branch fork hashes in independent contexts. Opaque simulator internals are not claimed exhaustively serialized.',
 'Ready TD target uses categorical probabilities at component means. Primary continuation therefore samples those same means with fixed paired uniform streams,without the tiny Gaussian evaluation residual. BC source,ready actor and ready target_actor weights are equal. This benchmark matches the intended target quadrature;it is not a comparison against a changed Actor continuation. Original MC labels mix three collection-policy continuations;MC Q1/Q2/Qmean are preserved but classified SEMANTICS_MISMATCH,no MC error or ranking acceptance asserted.',
 'Reward recursion uses actual reward at fork inclusive,gamma=.99,zero beyond success/termination/truncation or700step closure. All traces verified reward0/1 and actual finite return,not assumed from success formula. Postfork raw component means required zero clipping discrepancy.',
 '', '## Seed20005 final paired result',
 '|Candidate vs A|deltaQ1|deltaQ2|mean deltaG|negative/positive/tie streams|approx95% mean t interval|classification|',
 '|---|---:|---:|---:|---|---|---|']
 for x in s['seed20005'][:2]:
  xs=x['delta_g_samples'];neg=sum(z<-1e-4 for z in xs);pos=sum(z>1e-4 for z in xs);tie=len(xs)-neg-pos;ci=x['mean_t_interval_95_approx'];q=x['critics']['ready'];lines.append(f"|{x['actions'][1]}|{q['Q1']['delta_q']:+.9f}|{q['Q2']['delta_q']:+.9f}|{x['delta_g_mean']:+.9f}|{neg}/{pos}/{tie}|[{ci[0]:+.9f},{ci[1]:+.9f}]|{q['Q1']['classification']}|")
 lines+=['','For A-to-C,all six deltaG values are '+str(p['delta_g_samples'])+'. Two-sided sign p=.21875. A-to-D also has5negative/1positive,p=.21875. Thus Q1/Q2 preference is CONFIRMED,and repeated realized conflicts are CONFIRMED;negative conditional expected advantage is SUPPORTED but INCONCLUSIVE under preregistration. This is not6/6stable decline. All seed20005 episodes remain successful;the observed losses are discounted-return/timing effects,not proof this isolated action causes full-policy failure.',
 '', '## Independent batch results',
 '|Seed|fork|A-to-C deltaQ1|deltaQ2|six deltaG samples|classification Q1/Q2|',
 '|---|---:|---:|---:|---|---|']
 for x in b['pairs']:
  if x['actions']!=['A_BC','C_POST1250']:continue
  q=x['critics']['ready'];lines.append(f"|{x['seed']}|{x['fork']}|{q['Q1']['delta_q']:+.8f}|{q['Q2']['delta_q']:+.8f}|{[round(z,8) for z in x['delta_g_samples']]}|{q['Q1']['classification']}/{q['Q2']['classification']}|")
 lines += ['',f"Independent12pairs: {v['identifiable_pairs']} identifiable,{v['real_return_tie_pairs']} all-stream return ties,{v['unresolved_non_tie_pairs']} unresolved non-ties. Identified common twin mistakes={wrong}. Descriptive Q1up/Q2up/MCdown realizations={v['twin_wrong_realizations']}. Both types are separate;single-stream conflicts do not establish expected-value misranking. No outcome-based seed replacement occurred.",
 '', '## Counts, accuracy and advantage errors',
 f"Eight distinct contexts,24unique strict actionpairs,144paired-RNG comparisons. Identifiable pairs={s['identifiable_pairs']},all-stream return ties={s['real_return_tie_pairs']},unresolved non-ties={s['unresolved_non_tie_pairs']}. Pair tie fraction={s['real_return_tie_pairs']/24:.4f}. These exclude duplicate readiness candidate and do not count reused discovery twice.",
 '|Head|correct / identifiable|accuracy|mean absolute advantage error on identifiable pairs|',
 '|---|---|---:|---:|']
 for h,m in s['ready_metrics'].items():lines.append(f"|{h}|{m['correct']}/{m['denominator']}|{m['pairwise_accuracy']}|{m['mean_advantage_error_identifiable']}|")
 lines += ['',f"Identified common twin wrong pairs={s['twin_common_wrong_identifiable']};descriptive positive-twin/negative-return realizations={s['twin_positive_Q_negative_MC_realizations']}. Accuracy is restricted to return-identifiable pairs;excluding unresolved difficult pairs can select easier cases. Even100percent on a tiny denominator does not certify general ability.",
 'Predeclared return threshold1e-4,numeric tolerance1e-10,Q-direction tolerance1e-6. A pair is a REAL_RETURN_TIE only if all tested differences are within threshold. Non-ties need two-sided paired sign p<=.05 and approximate95percent mean t interval beyond threshold before directional classification. Sign test concerns median;small-sample t interval assumes suitable iid difference distribution and is approximate for the mean. Criteria are per-pair exploratory,not familywise adjusted or a nonparametric confidence guarantee on expected advantage. Ties never count correct.',
 'Group summaries are in final_summary.json and round2/analysis.json,round3/analysis.json. Discovery has one context per group;independent has four BC-prefix task-critical contexts. This does not provide a controlled longitudinal error-versus-Actor-training-stage estimate. Readiness andBC are identical;normal post1250is the optimized candidate,not a new training intervention.']
 lines += ['', '## Why existing readiness did not detect it',
 f"At actual unlock140000steps:Qmean-MC Spearman={s['old_readiness_actual']['qmean_mc_spearman']:.6f};TD Q1/Q2 MAE={s['old_readiness_actual']['td_e1_mae']:.9f}/{s['old_readiness_actual']['td_e2_mae']:.9f};finite={s['old_readiness_actual']['numeric_finite']},overall_ready_v2={s['old_readiness_actual']['overall_ready_v2']}.",
 'The historical .98974 correlation is a restricted BC-success probe,not the actual whole readiness unlock statistic. Its .99199 fixed-action correlation demonstrates why behavioral correlation is not an action-advantage test. History dependence and nonzero candidate gradients remain useful structural observations. Small TD residual and stable scale verify consistency/health against learned targets;two heads can share error. None tests signs or magnitudes of fixed-history action differences.',
 'The six capabilities remain distinct:behavioral return prediction supported;history use confirmed previously;current action sensitivity confirmed previously;fixed-history ranking only partially evaluated here;counterfactual advantage magnitude not globally certified;applicability to updated full Actor continuation not certified by this fixed-BC benchmark. Stage3 offline replay includes Stage2 validation seeds,so these cannot be treated as independent ready-TD validation. Independent data here are newly generated andnotfitted.',
 '', '## Classification and collapse implications',
 '**CONFIRMED:**strict paired protocol completed,semantic target matched,seed20005positive Q1/Q2 changes with5/6negative realized returns,andoldreadiness lacks conditional action-ranking acceptance. Negative realizations are repeatable observations,not necessarily an erroneous expectation.',
 '**SUPPORTED:**seed20005negative empirical mean;conditional-supervision/approximation weakness remains plausible. If independent identified common errors appear,they support local misranking only within reported contexts under exploratory criteria. Nearby history coverage exists in the already completed CPU audit,so blanket history absence is not established.',
 '**INCONCLUSIVE:**seed20005true expected advantage sign,global ranking reliability,need to change supervision rather than approximation/history representation,andunique upstream collapse cause. No claim that both Critics are wrong against mismatched continuation;original MC remains unevaluated for matched counterfactual semantics.',
 'Historical frozen-ready and original-MC normal Actor optimization can improve surrogate Q and lose closed-loop competence. This establishes policy-level surrogate/competence failure;later TDbootstrap or later critic/replay evolution is not necessary. Present finite-action observations do not prove a universal gradient-sign reversal or that one delayed-success action uniquely causes full Actor collapse. Ordinary continuation-dependent Q is expected in RL. Conditional label coverage,approximation,state/history aliasing,andchanged-policy continuation remain unresolved upstream alternatives.',
 '', '## Preservation, stopping and sole proposed next step',
 f"Newepisodes={s['new_episodes']},environmentsteps={s['env_steps']},Actor/Criticupdates=0. Allthree simulator invocations initialized/used/closed4/4/4,workerexits0,logicalnpu:0only,oneexperimentatatime. Simulatorwallseconds={s['wall_seconds']}. Completed episodes were never rerun.",
 f"All{safety['hashed_files']}baseline production/formal/input/historicalfilesunchanged. Rootfusion_result.jsonbefore/after={safety['fusion_exists_before']}/{safety['fusion_exists_after']};runtime-generated fusionfiles retained. Noresidualsimulator/diagnosticprocesses. Rawtraces,preregistration,resultJSONs,andlogsretained;noformalcheckpointorproductionedit. CPUcoverage andmetricguardfiles were prepared before final narrowed scope and do not constitute a production gate or successful repair.",
 'Only proposed future work,not executed:if the user later authorizes it,resolve conditional expected advantage uncertainty on the recorded conflict contexts before selecting a supervision or approximation repair. No further seeds,streams,training,gate design or repair launched after the single independent batch.',
 '', '## Evidence',
 'round1/ and round2_extension/:raw discovery and supplemental traces/results;round2/:combined analysis without double counting;round3/:one independent batch;round4/conditional_coverage.json:previously completed CPU scan;existing_audit.json:five required reports andnine production source snippets;old_readiness_at140000.json:actual gate row;safety_before/after.json:preservation andall144tracechecks;final_summary.json:machine-readable classifications andallpairs.',
 '', 'CRITIC COUNTERFACTUAL ACCEPTANCE TEST COMPLETE','FORMAL TRAINING REMAINS STOPPED']
 (HERE/'FINAL_REPORT.md').write_text('\n'.join(lines)+'\n')
 # Final reports of the completed independent and offline analysis rounds.
 (HERE/'round3/ROUND_REPORT.md').write_text('''# Round3: fixed independent batch, then stop
Previous:seed20005fiveofsixnegative return differences,butconditionalmeanunresolved. Strongestremainingquestion:isthereindependentlocalaction-rankingconflict? Onlypreregistered20088-20091and42001-42006wereused;firstgrippersignchangeafter120withfallback350;retainallreferencefailures. Exactforkphysical/history/RNN/RNG/candidatehashesmatched. PrimarycontinuationmatchesreadyTDcategoricalmeans. Nooptimizerorproductionchanges.
Result:seeanalysis.jsonandsummarybelow. Correct/tie/unresolved/wrongclassificationusespredeclaredthresholdsandstatisticalguard;tiedreturnsnevercountcorrect. No extrapolationfromfewidentifiedpairsorcorrelatedactions.Noalternativecontexts,streamsornewexperimentselectedafterresults.
Decision:STOP.Userhardconstraintfulfilleduponthisbatchcompletion.Workersclosednormally.Noformaltraining.NextstepisproposalonlyinFINAL_REPORT.md.
'''+json.dumps(b['summary']['all'],indent=2)+'\n')
 (HERE/'round4/ROUND_REPORT.md').write_text('''# Existing CPU coverage audit;no new simulator experiment
Prepared and completed during supplemental streams,before user final narrowed stop instruction. ReadinessreplayandoriginalMCtrainingwindowswerequeriedforthefourfixeddiscoverycontexts.No fitting,optimizerornewcounterfactualepisode. Neighborswithin calibratedhistoryradius do not identify true action advantages or unique approximation/label cause. Detailedtables inconditional_coverage.json. No further Round4experiment performed.
''')
if __name__=='__main__':main()
